### ISSUE TITLE
[Feature request] Determine connection URL

### ISSUE THREAD

**Issue by nikolasburk** [prisma/upgrade#1]
Figuring out the right connection URL that I need to put into the Prisma schema can be tricky. I think it would be awesome if the CLI could compose it for me by putting together the info from the Docker Compose file and prisma.yml. 

## Example

For example, for this Docker Compose config:

```yml
databases:
  default:
    connector: postgres
    host: host.docker.internal
    database: mydb
    schema: public
    user: janedoe
    password: janedoe
    ssl: false
    rawAccess: true
    port: '5432'
    migrations: true
```

And this prisma.yml:

```yml
endpoint: http://localhost:4466/myservice/dev
```

It would derive the following connection URL:

```
postgresql://janedoe:randompassword@localhost:5432/mydb?schema=myservice$dev
```

## Concerns

We should make sure this doesn't feel invasive, it can be scary when tools fiddle with your database credentials.
