### ISSUE TITLE
prisma.yml doesn't handle comments or directory paths

### ISSUE THREAD

**Issue by louisrli** [prisma/upgrade#20]
Example errors:
```
Error Expected "datasource", "enum", "generator", "model", "type", or end of input but "/" found.
```

```
Error Expected "datasource", "enum", "generator", "model", "type", or end of input but "#" found.
```

```yaml
# Specifies the HTTP endpoint of your Prisma API.
endpoint: ${env:PRISMA_ENDPOINT}

# Defines your models, each model is mapped to the database as a table.
datamodel:
  - user.prisma
  - studyguide.prisma
  - schedule.prisma

# Specifies the language and directory for the generated Prisma client.
generate:
  - generator: typescript-client
    output: ../src/generated/prisma-client

# Ensures Prisma client is re-generated after a datamodel change.
hooks:
  post-deploy:
    - echo "Deployment finished"
    - graphql get-schema --project db
    - graphql codegen
# If specified, the `secret` must be used to generate a JWT which is attached
# to the `Authorization` header of HTTP requests made against the Prisma API.
# Note that this is the same as the env variable for the Prisma CLI.
secret: ${env:PRISMA_MANAGEMENT_API_SECRET}
```

Even using a really basic `prisma.yml` doesn't do it, it's still giving an error that `/` is found.
```
datamodel:
  - user.prisma
  - studyguide.prisma
  - schedule.prisma
secret: 'foo'
endpoint: 'bar'
```

This is without providing any schema:
```
/Users/louis/branches/srs/server/node_modules/.bin/prisma-upgrade prisma.bak/prisma.yml
```

Now, if I run with a schema file like so:
```
 /Users/louis/branches/srs/server/node_modules/.bin/prisma-upgrade prisma.bak/prisma.yml prisma.bak/combined.prisma
```

I get this:
```
Error Expected "datasource", "enum", "generator", "model", "type", or end of input but "#" found.
```

which I assume that whatever parser this tool has, it doesn't handle comments well.

In any case, I feel like I'm following the [directions](https://www.prisma.io/docs/guides/upgrade-from-prisma-1/how-to-upgrade#prisma-upgrade-cli), but the tool's not very stable for my particular case
