### ISSUE TITLE
[Feature Request] Support endpoint environment variable

### ISSUE THREAD

**Issue by williamluke4** [prisma/upgrade#3]
_prisma.yml_
```yml
endpoint: ${env:PRISMA_ENDPOINT}
secret: ${env:PRISMA_SECRET}

datamodel: 
  - users.prisma
  - general.prisma
  - trips.prisma
  - properties.prisma
  - transfers.prisma
  - airports.prisma
  - misc.prisma
  - flights.prisma
  - chatRooms.prisma
  - file.prisma
```
